sudo: false
dist: trusty

language: node_js

cache:
  directories:
    - $HOME/.npm

jobs:
  include:
    - stage: release
      node_js: '8'
      script:
        - npm run semantic-release

stages:
  - name: release
    if: branch = master AND type = push AND fork = false
